name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying to production..."